repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black # code formatting
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort # import sorting
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8 # check errors -- can be annoying